name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        node-version: ${{ matrix.node-version }}
    - name: dependencies
      run: |
        eval "$(ssh-agent -s)"
        start-ssh-agent.cmd
    - name: Build
      run: |
        npm install
        npx webpack
        
